export const GET__COURSES="GET__COURSES"
export const UPDATE__COURSE__LIST="UPDATE__COURSE__LIST"
export const DELETE__COURSE='DELETE__COURSE'
export const GET_ENROLLED_COURSES_LIST="GET_ENROLLED_COURSES_LIST"
